services:
  backend:
    build: ./Backend
    ports:
      - "2000:2000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/stockpharmacy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=/api
    depends_on:
      - backend

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: system
      MYSQL_DATABASE: stockpharmacy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-psystem"]
      interval: 5s
      timeout: 10s
      retries: 15
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: