apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sweetnex/pharma-backend:latest
          ports:
            - containerPort: 2000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/stockpharmacy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:  # Use Secret instead of plain text
                secretKeyRef:
                  name: mysql-secret
                  key: password
          livenessProbe:  # Add health checks
            httpGet:
              path: /actuator/health
              port: 2000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
  type: ClusterIP  # Good for internal communication