apiVersion: v1
kind: Namespace
metadata:
  name: logging  # Create namespace first
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30002
  selector:
    app: kibana  # Must match pod labels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  selector:  # Required deployment selector
    matchLabels:
      app: kibana
  template:
    metadata:  # Pod labels must match selector
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.13.4
        ports:
        - containerPort: 5601
        env:  # Add basic configuration
        - name: ELASTICSEARCH_HOSTS